### ISSUE TITLE
Correção no loop FightApplication.ts

### ISSUE THREAD

**Issue by MathhMolina** [RPlima/RPG-NodeJs#1]
Na classe FightApplication.ts, deve ser allterado o `while(player.LifePoints > 0 || monster.LifePoints > 0);` para `while(player.LifePoints > 0 && monster.LifePoints > 0);` , pois a luta deve acontecer se a vida do player for maior que 0 **E** a vida do monstro for maior que 0, e não **OU**

**Comment by RPlima** [comment]
Foi resolvido com o commit logo acima
